In [1]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from sklearn.preprocessing import LabelEncoder

# default module
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import KFold

In [3]:
import warnings
warnings.filterwarnings('ignore')

###### 랜포 중요도에 따른 피처

In [4]:
def select_important_feautre(columns, feature_importance, num):
    
    #딕셔너리
    dic = {}
    for value in [list(v) for v in zip(columns, feature_importance)]:
        dic[str(value[1])] = value[0] 
    
    #피처 중요도
    f_i = list(feature_importance)
    f_i.sort(reverse=True)
    
    
    #n개 뽑기
    result = []
    for i in range(0, num):
        result.append(dic[str(f_i[i])])
    
    return result

In [5]:
def cross_val_score_custom(model, x, y, cv, dev = 0):
    
    print('\n\n')
    
    result = []
    
    for train_idx, test_idx in cv.split(x):
        
        new_x_train = x.iloc[train_idx, :]
        new_y_train = y.iloc[train_idx]
        
        new_x_test = x.iloc[test_idx, :]
        new_y_test = y.iloc[test_idx]
        
        model.fit(new_x_train, new_y_train)
        
        temp = np.mean(f1_score(new_y_test, model.predict(new_x_test), average=None))
        
        if dev:
            print('dev Mode # : {}'.format(temp))
        
        result.append(temp)
    
    print('\n\n')
    
    return np.mean(result)

In [6]:
def get_oof(model, x_train, y_train, x_test):
    
    le = LabelEncoder()
    le.fit(y_train)
    y_train = pd.Series(le.transform(y_train))
    
    oof_train = np.zeros((x_train.shape[0],))
    oof_test = np.zeros((x_test.shape[0],))
    oof_test_skf = np.empty((5, x_test.shape[0]))
    
    for i, (train_idx, test_idx) in enumerate(KFold(n_splits=5).split(x_train)):
        
        x_tr = x_train.iloc[train_idx, :]
        y_tr = y_train.iloc[train_idx]
        x_te = x_train.iloc[test_idx, :]
        
        model.fit(x_tr, y_tr)

        oof_train[test_idx] = model.predict(x_te)
        oof_test_skf[i, :] = model.predict(x_test)
    
    # version 1
    # oof_test[:] = np.round(oof_test_skf.mean(axis=0))
    
    # version 2
    oof_test[:] = pd.DataFrame(oof_test_skf).apply(lambda v: v.value_counts().idxmax(), axis=0)
    
    oof_train = [int(v) for v in oof_train]
    oof_train = le.inverse_transform(oof_train)
    
    oof_test = [int(v) for v in oof_test]
    oof_test = le.inverse_transform(oof_test)
    
    return oof_train.reshape(-1,1), oof_test.reshape(-1,1)

###### 데이터 로드

In [9]:
x_data = pd.read_csv('./data/data.csv')
# label 불러오기
y_data = pd.read_excel('./data/label.xlsx')
y_data['hash'] = y_data['hash'].apply(lambda v: v[:-4].upper())
# y_data.columns = ['hash', 'is_mal']

In [12]:
data = pd.merge(y_data, x_data, on='hash', how = 'left')

In [14]:
data = data.fillna(0)

In [9]:
# data_extra = pd.read_csv('./data/data_extra.csv').drop(['Unnamed: 0'], axis = 1)

In [10]:
# data_extra['is_mal'] = 0

In [11]:
# data = pd.concat([data, data_extra], sort=False).drop_duplicates()

In [12]:
# for i, v in enumerate(data.columns):
#     print("{}: {}".format(i, v))

###### train test data split

In [17]:
x_data = data.iloc[:,2:]
y_data = data.iloc[:,1]

In [23]:
def get_cv_score(x_data, y_data, model, k):
    
    cv = KFold(k, shuffle=True, random_state=0)
    
    train_score = []
    cv_score = []
    
    for idx_train, idx_test in cv.split(X=x_data, y=y_data):
        
        x_train = x_data.iloc[idx_train]
        x_test = x_data.iloc[idx_test]
        y_train = y_data.iloc[idx_train]
        y_test = y_data.iloc[idx_test]

        model.fit(x_train, y_train)
        
        train_score.append(model.score(x_train, y_train))
        cv_score.append(model.score(x_test, y_test))
    
    return train_score, cv_score

In [24]:
rf = RandomForestClassifier(n_estimators=500, random_state=42, n_jobs=-1, max_depth=28)

In [25]:
train_score, cv_score = get_cv_score(x_data=x_data, y_data=y_data, k=5, model=rf)
# print("========[{}]========".format(feature_set_name[nu]))
print("train list : {}".format(train_score))
print("cv list : {}".format(cv_score))
print("train: {} \n cv: {}".format(np.mean(train_score), np.mean(cv_score)))
print("\n")

train list : [0.999625, 0.99925, 0.999125, 0.999375, 0.9995]
cv list : [0.945, 0.9475, 0.945, 0.937, 0.9505]
train: 0.999375 
 cv: 0.945




In [15]:
x_test = pd.read_csv('./data/data_test.csv').drop(['Unnamed: 0'], axis = 1)

In [16]:
result = pd.read_csv('./data/result_malware_student_songwonho.csv')

In [17]:
x_test

hash  TimeDateStamp  MajorLinkerVersion  \
0     000384C2E991519DB9B49C8FF39E8E89     1260053446                   6   
1     000C8778DAA1276584679CD21F2037ED      708992537                   2   
2     001193DED99300A380F6DCA28C61236D     1144432766                   6   
3     00130CDF56DEB3A8F894E29565D5A760              0                   2   
4     00131ECCFDFAD08DABA3742B7142258A     1373857134                   9   
5     0023077CC67A46FDE163AF616910D6CC     1345687972                   8   
6     002768F23D157D643138C798890B3B64     1485906012                  10   
7     0029A2BBE72A871392CF0ECD7E0AFFE7     1260053452                   6   
8     002DC4A8990FFEC5DFAEAED8FECE41DE     1420504568                   5   
9     003173C2FB52AEF695D83EC529D5C70D     1327116325                   8   
10    00329889A1C677BBA7C0E61FA979D798     1453548117                  11   
11    0036062324E0D08A1CA1994BE37EB63F     1257193455                   8   
12    0048D7A1945B3E32436925731CB3A845     1504719372                  14   
13    005FDF1B40E19157F221801F46AFC824     1397394628                   6   
14    006B1EE36E700933ECFC0F88B5992E72     1270142225                   6   
15    006E64419B4E0F418EB8913EAC26A7D3     1468432647                   8   
16    00727CB11872978117EA96F30936F5AE     1430423931                  10   
17    00740D797D7A13711FE7F24571264987     1260053446                   6   
18    00779FB34EF8632CCACA9D239D93DAAC     1091599118                   7   
19    008672B216141EE94B4551D28D0845A0     1469408157                   6   
20    0093B8511EB7F2BB8BF89F692F4FD297     1508329660                  14   
21    00A91F73CA1F25628A05ACC11BD4FD7F     1288806717                   6   
22    00AE44BA012C6E06970D1AFE1880338F     1528165435                   6   
23    00B623A40CF9AF328BB379B59FA51ABF     1488498546                  10   
24    00BA21AB41D25D21D2D26446A06B9A4B     1468633369                  14   
25    00C6236BEE6C07419B072D77C04FD85F     1478709469                   2   
26    00C8DD0A2953B5FECA76EEF522E4EE58     1524521892                   9   
27    00D024AFB7DD46F52F0F3A8447AE76F3     1411643196                   8   
28    00D0C60B843A53FCD5CF634D8592435D     1369890405                   6   
29    00DB990DC453005AF7EABFD2A0B53191     1501001102                  11   
...                                ...            ...                 ...   
9864  FF20623FF29B2771B94A123BDC5C8E86     1459303632                   0   
9865  FF2845690CDFB29B77B05E6DAA05B20F     1437580244                   6   
9866  FF2B89BBE8FF1BCECDF7E56E851C4448     1465521153                  48   
9867  FF31B7AE2DB5951529088461F7D68F94      708992537                   2   
9868  FF356C1867C857833AD61B95F3070D6D     1502352550                   2   
9869  FF39A4334A5169C187DC8FADAFE34858     1332186990                   2   
9870  FF420920DCB901B910D3949F598CAEC8     1260053446                   6   
9871  FF4388E9A504F818DD219561B49DF340     1319213574                   6   
9872  FF55E3649B20AA2BE74A26F6079C62C3     1027992322                   5   
9873  FF576778A11B3A63E2596BE43F7085CF     1485243663                  12   
9874  FF698F0595E5D7B5D7122C6408A0CDDE     1125959230                  10   
9875  FF69D856155649CFF50F84FEF93C9966     1339084793                   2   
9876  FF6D76E60E449B242AC2CEF4DCF97C2C      708992537                   2   
9877  FF7143CD0F2A8E13160B828757C44F66     1495540732                  14   
9878  FF7319B0BF3A8AA81153DB2DED8C08A2     1502510999                   5   
9879  FF7518B10D8E130207D23A17239F76D7     1338053012                   6   
9880  FF7B65C5D7FE591CBBBCC272CB20FB4B     1426238465                   9   
9881  FF7CF3A11CE3BA01B5D0846EEB649844     1260053532                   6   
9882  FF7F08080C648841AAA800CD9B29CEB0     1399838739                   6   
9883  FF7FB581028DB9821E76A4D1EBAD3C48     1482957111                   9   
9884  FF86DDC2E8A5A1F450D444DC

In [19]:
result = result['hash'].apply(lambda v: v[:-4].upper())

In [21]:
result = result.to_frame()

In [22]:
data = pd.merge(result, x_test, on='hash', how = 'left')

In [26]:
data = data.fillna(0)

In [29]:
data = data.drop(['hash'], axis = 1)

In [32]:
x_test = data

In [33]:
rf = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=50, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

xgb = XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.8, gamma=0.2, learning_rate=0.1,
       max_delta_step=0, max_depth=10, min_child_weight=1, missing=None,
       n_estimators=600, n_jobs=1, nthread=1, objective='binary:logistic',
       random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
       seed=None, silent=True, subsample=0.8)

tree = DecisionTreeClassifier(criterion='entropy', max_depth=28, random_state=0)

In [34]:
oof_train_rf, oof_test_rf = get_oof(rf, x_train, y_train, x_test)
oof_train_xgb, oof_test_xgb = get_oof(xgb, x_train, y_train, x_test)
oof_train_tree, oof_test_tree = get_oof(tree, x_train, y_train, x_test)

In [35]:
x_train = np.concatenate((oof_train_rf, oof_train_xgb, oof_train_tree), axis = 1)
x_train = pd.DataFrame(x_train)

x_test = np.concatenate((oof_test_rf, oof_test_xgb, oof_test_tree), axis = 1)
x_test = pd.DataFrame(x_test)

In [36]:
oof_train_rf

array([[0],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [37]:
oof_train_xgb

array([[0],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [38]:
oof_train_tree

array([[0],
       [1],
       [0],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [39]:
x_train.columns = ['rf', 'xgb', 'tree']
x_test.columns = ['rf', 'xgb', 'tree']

In [40]:
x_train

rf  xgb  tree
0      0    0     0
1      1    1     1
2      1    1     0
3      1    1     1
4      1    1     1
5      1    1     1
6      0    0     0
7      1    1     1
8      0    0     0
9      1    1     1
10     0    0     0
11     1    1     1
12     1    1     1
13     1    1     0
14     1    1     1
15     0    0     0
16     1    1     1
17     1    1     1
18     1    1     1
19     0    0     0
20     1    0     0
21     1    1     1
22     1    1     1
23     1    1     1
24     0    0     0
25     0    0     0
26     1    1     1
27     1    1     1
28     1    1     1
29     0    0     0
...   ..  ...   ...
9970   0    0     0
9971   0    0     0
9972   1    1     1
9973   1    1     1
9974   1    1     1
9975   1    1     1
9976   1    1     1
9977   1    1     1
9978   1    1     1
9979   1    1     0
9980   1    1     1
9981   1    1     1
9982   1    1     1
9983   1    1     1
9984   0    0     0
9985   1    1     1
9986   1    1     1
9987   1    1     0
9988   1    1     1
9989   1    1     1
9990   1    1     1
9991   1    1     1
9992   1    1     1
9993   1    1     0
9994   1    1     1
9995   1    1     1
9996   1    1     1
9997   1    1     1
9998   1    1     1
9999   1    1     1

[10000 rows x 3 columns]

## layer 2

In [41]:
x_test.apply(lambda v: v.value_counts().idxmax(), axis=1)

0       1
1       1
2       0
3       0
4       1
5       1
6       0
7       1
8       1
9       1
10      0
11      0
12      0
13      1
14      1
15      1
16      0
17      1
18      1
19      1
20      0
21      1
22      1
23      1
24      0
25      1
26      1
27      1
28      0
29      1
       ..
9970    1
9971    0
9972    0
9973    1
9974    1
9975    1
9976    0
9977    1
9978    1
9979    0
9980    1
9981    1
9982    1
9983    1
9984    1
9985    1
9986    0
9987    1
9988    1
9989    1
9990    0
9991    1
9992    1
9993    0
9994    0
9995    1
9996    0
9997    1
9998    1
9999    0
Length: 10000, dtype: int64

In [44]:
rf_l2 = RandomForestClassifier(n_estimators=3, random_state=3, max_depth=3, n_jobs=-1)

In [45]:
rf_l2.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=3, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=3, n_jobs=-1,
            oob_score=False, random_state=3, verbose=0, warm_start=False)

In [47]:
print("훈련 세트 정확도: {:.3f}".format(rf_l2.score(x_train, y_train)))

훈련 세트 정확도: 0.952


In [49]:
rf_l2.predict(x_test)

array([1, 1, 0, ..., 1, 1, 0], dtype=int64)

In [51]:
result['is_mal'] = rf_l2.predict(x_test)

In [56]:
result['hash'] = result['hash'].apply(lambda v: (v + '.vir').lower())

In [58]:
result.to_csv('./first_try.csv')

In [ ]:
print("크로스발리데이션 세트 정확도: {:.3f}".format(rf_l2.score(x_test, y_cv)))

In [49]:
print(classification_report(y_cv, tree.predict(x_cv)))

             precision    recall  f1-score   support

          0       0.92      0.90      0.91      2244
          1       0.90      0.92      0.91      2101

avg / total       0.91      0.91      0.91      4345



In [270]:
from sklearn.metrics import accuracy_score


In [271]:
accuracy_score(y_cv, x_test.apply(lambda v: v.value_counts().idxmax(), axis=1))

0.944